# Render.com Deployment Configuration
# For Advanced Botnet Research Framework

services:
  # C2 Server - Main Application
  - type: web
    name: botnet-c2-server
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: RESEARCH_MODE
        value: "true"
      - key: C2_MODE
        value: "RESEARCH"
      - key: ETHICAL_CONTROLS
        value: "strict"
      - key: COMPLIANCE_LOGGING
        value: "enabled"
      - key: C2_HTTP_PORT
        value: "8080"
      - key: C2_HTTPS_PORT
        value: "8443"
      - key: C2_WEBSOCKET_PORT
        value: "8081"
      - key: C2_ADMIN_PORT
        value: "9090"

  # Web Dashboard (Static Site)
  - type: static
    name: botnet-dashboard
    buildCommand: "echo 'Static files ready'"
    publishPath: ./c2-server/web-dashboard
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: botnet-postgres
    databaseName: botnet_research
    user: botnet
    plan: starter
    region: oregon

  - name: botnet-redis
    plan: starter
    region: oregon
